#! ruby -Ku
# -*- coding: utf-8 -*-

require "bundler/setup"
Bundler.require(:default)
require "resque/tasks"
require "./app2"
require "./job"
require 'resque_scheduler/tasks'

task "resque:setup" do
    ENV['QUEUE'] = '*'
    
      log_file = ENV['RESQUE_LOG_PATH']
  Resque.logger = Logger.new(log_file) unless log_file.nil?
  Resque.logger.level = Logger::DEBUG
    
end

task "jobs:work" => "resque:work"